### ISSUE TITLE
but I am using pi3 ，its pins has not same to your , can you tell me how to use .

### ISSUE THREAD

**Issue by buzai** [plenkyman/RFID_RC522_Python3_TheDoor#2]
`+-----+-----+---------+------+---+---Pi 3---+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 | ALT0 | 1 |  3 || 4  |   |      | 5V      |     |     |
 |   3 |   9 |   SCL.1 | ALT0 | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 0 |  7 || 8  | 1 | ALT5 | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | ALT5 | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 |   IN | 0 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |   IN | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |   IN | 0 | 15 || 16 | 0 | IN   | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 0 | IN   | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI | ALT0 | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO | ALT0 | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK | ALT0 | 0 | 23 || 24 | 1 | OUT  | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 1 | OUT  | CE1     | 11  | 7   |
 |   0 |  30 |   SDA.0 |   IN | 1 | 27 || 28 | 1 | IN   | SCL.0   | 31  | 1   |
 |   5 |  21 | GPIO.21 |   IN | 1 | 29 || 30 |   |      | 0v      |     |     |
 |   6 |  22 | GPIO.22 |   IN | 1 | 31 || 32 | 0 | IN   | GPIO.26 | 26  | 12  |
 |  13 |  23 | GPIO.23 |   IN | 0 | 33 || 34 |   |      | 0v      |     |     |
 |  19 |  24 | GPIO.24 |   IN | 0 | 35 || 36 | 0 | IN   | GPIO.27 | 27  | 16  |
 |  26 |  25 | GPIO.25 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO.28 | 28  | 20  |
 |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO.29 | 29  | 21  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+---Pi 3---+---+------+---------+-----+-----+
`

my english is not good. this is pi gpio .

**Comment by buzai** [comment]
i think you should copy the gpio to the sublimtext ,so it wil see ok.

**Comment by plenkyman** [comment]
i think that pi 2 and pi 3 share the same Board layout.
for your in formation: http://pi.gadgetoid.com/pinout

in help_installation.txt :
VCC- pin 1, 3.3 volts 
RST- pin 22, GPIO25
GND- pins, 6, 9, 14, 20, or 25,
MISO- pin 21, GPIO9
MOSI- pin 19, GPIO10
SCK- pin 23, GPIO11
NSS- pin 24, GPIO7
IRQ- Don’t Attach to rpi

for LED's, strike and exit button run command line: setdoorprefs or edit TheDoorPrefs.py to your liking.

**Comment by plenkyman** [comment]
in help_installation.txt :
VCC- pin 1, 3.3 volts 
RST- pin 22, GPIO25
GND- pins, 6, 9, 14, 20, or 25,
MISO- pin 21, GPIO9
MOSI- pin 19, GPIO10
SCK- pin 23, GPIO11
NSS- pin 24, GPIO7
IRQ- Don’t Attach to rpi

for LED's, strike and exit button run command line: setdoorprefs or edit TheDoorPrefs.py to your liking.

**Comment by buzai** [comment]
I consulted a lot of information, I also found that they should be the same, I'm sorry this is my question, thank you very much for your answer.
